import { config } from "dotenv";
import { dirname } from "path";
import { fileURLToPath } from "url";

config();

export default {
  env: process.env.NODE_ENV,
  port: process.env.PORT,
  dirname: dirname(fileURLToPath(import.meta.url)),
  
  cookieSecret: process.env.COOKIE_SECRET,
  jwtSecret: process.env.JWT_SECRET,

  adminUsername: process.env.ADMIN_USERNAME,
  adminPassword: process.env.ADMIN_PASSWORD,

  linkedInIndustryGroups: [
    { label: "Professional Services", industries: [] },
    { label: "Hardware Manufacturing", industries: [] },
    { label: "Information Technology", industries: [] },
    { label: "Education", industries: [] },
    { label: "Healthcare", industries: [] },
    { label: "MedTech", industries: [] },
    { label: "FinTech", industries: [] },
    { label: "EdTech", industries: [] },
    { label: "Aerospace", industries: [] },
    { label: "Logistics", industries: [] },
    { label: "Real Estate", industries: [] },
    { label: "Construction", industries: [] },
    { label: "Travel & Tourism", industries: [] },
    { label: "Energy & Raw Materials", industries: [] },
    { label: "Automotive", industries: [] },
    { label: "Retail & E-Commerce", industries: [] },
    { label: "Fast-moving Consumer Goods", industries: [] },
    { label: "Entertainment & Culture", industries: [] },
    { label: "Sports", industries: [] },
    { label: "Restaurants", industries: [] },
    { label: "Banking & Insurance", industries: [] },
    { label: "Media & Communication", industries: [] },
    { label: "Sports", industries: [] },
  ],

  cookieFlags: [{ name: "", label: "" }],
  privacyFlags: [{ name: "", label: "" }],
  negativePrivacyFlags: [{ name: "", label: "" }],
};

const linkedInIndustries = [
  "ProfessionalServices",
  "Manufacturing",
  "Technology,InformationandMedia",
  "FinancialServices",
  "Education",
  "Chiropractors",
  "DefenseandSpaceManufacturing",
  "Optometrists",
  "ComputerHardwareManufacturing",
  "SoftwareDevelopment",
  "ComputerNetworkingProducts",
  "TransportationEquipmentManufacturing",
  "Technology,InformationandInternet",
  "Physical,OccupationalandSpeechTherapists",
  "SemiconductorManufacturing",
  "Telecommunications",
  "LawPractice",
  "HousingPrograms",
  "LegalServices",
  "BusinessConsultingandServices",
  "BiotechnologyResearch",
  "FamilyPlanningCenters",
  "MedicalPractices",
  "TransportationPrograms",
  "HospitalsandHealthCare",
  "UtilitiesAdministration",
  "PharmaceuticalManufacturing",
  "OutpatientCareCenters",
  "VeterinaryServices",
  "MedicalEquipmentManufacturing",
  "SpaceResearchandTechnology",
  "MotorVehiclePartsManufacturing",
  "PersonalCareProductManufacturing",
  "RetailApparelandFashion",
  "SportingGoodsManufacturing",
  "TobaccoManufacturing",
  "MedicalandDiagnosticLaboratories",
  "RetailGroceries",
  "FoodandBeverageManufacturing",
  "OilExtraction",
  "ComputersandElectronicsManufacturing",
  "NaturalGasExtraction",
  "FurnitureandHomeFurnishingsManufacturing",
  "HomeHealthCareServices",
  "Retail",
  "EmbeddedSoftwareProducts",
  "EntertainmentProviders",
  "MobileComputingSoftwareProducts",
  "GamblingFacilitiesandCasinos",
  "AmbulanceServices",
  "DesktopComputingSoftwareProducts",
  "ITSystemCustomSoftwareDevelopment",
  "TravelArrangements",
  "ITSystemOperationsandMaintenance",
  "Hospitality",
  "ITSystemInstallationandDisposal",
  "Restaurants",
  "ITSystemTrainingandSupport",
  "Hospitals",
  "SpectatorSports",
  "ITSystemDataServices",
  "FoodandBeverageServices",
  "ITSystemTestingandEvaluation",
  "Movies,Videos,andSound",
  "BroadcastMediaProductionandDistribution",
  "Museums,HistoricalSites,andZoos",
  "ArtistsandWriters",
  "PerformingArts",
  "RecreationalFacilities",
  "Banking",
  "Insurance",
  "NursingHomesandResidentialCareFacilities",
  "RealEstate",
  "InvestmentBanking",
  "InvestmentManagement",
  "Accounting",
  "Construction",
  "WholesaleBuildingMaterials",
  "ArchitectureandPlanning",
  "CivilEngineering",
  "InternetNews",
  "AviationandAerospaceComponentManufacturing",
  "Blogs",
  "MotorVehicleManufacturing",
  "InteriorDesign",
  "ChemicalManufacturing",
  "SocialNetworkingPlatforms",
  "MachineryManufacturing",
  "HouseholdandInstitutionalFurnitureManufacturing",
  "BusinessIntelligencePlatforms",
  "Mining",
  "BusinessContent",
  "OilandGas",
  "DataSecuritySoftwareProducts",
  "Shipbuilding",
  "Utilities",
  "MobileGamingApps",
  "TextileManufacturing",
  "InternetPublishing",
  "PaperandForestProductManufacturing",
  "MediaandTelecommunications",
  "RailroadEquipmentManufacturing",
  "BlockchainServices",
  "Farming",
  "ServicesfortheElderlyandDisabled",
  "Ranching",
  "DairyProductManufacturing",
  "OfficeFurnitureandFixturesManufacturing",
  "Fisheries",
  "CommunityServices",
  "PrimaryandSecondaryEducation",
  "HigherEducation",
  "EducationAdministrationPrograms",
  "ResearchServices",
  "MattressandBlindsManufacturing",
  "ArmedForces",
  "LegislativeOffices",
  "AdministrationofJustice",
  "InternationalAffairs",
  "EmergencyandReliefServices",
  "GovernmentAdministration",
  "ExecutiveOffices",
  "LawEnforcement",
  "VocationalRehabilitationServices",
  "PublicSafety",
  "PublicPolicyOffices",
  "AdvertisingServices",
  "ChildDayCareServices",
  "NewspaperPublishing",
  "PerformingArtsandSpectatorSports",
  "BookandPeriodicalPublishing",
  "PrintingServices",
  "InformationServices",
  "Libraries",
  "TheaterCompanies",
  "EnvironmentalServices",
  "FreightandPackageTransportation",
  "DanceCompanies",
  "IndividualandFamilyServices",
  "ReligiousInstitutions",
  "CivicandSocialOrganizations",
  "ConsumerServices",
  "CircusesandMagicShows",
  "TruckTransportation",
  "WarehousingandStorage",
  "SportsTeamsandClubs",
  "AirlinesandAviation",
  "MaritimeTransportation",
  "Racetracks",
  "ITServicesandITConsulting",
  "MarketResearch",
  "PublicRelationsandCommunicationsServices",
  "DesignServices",
  "Non-profitOrganizations",
  "Fundraising",
  "StrategicManagementServices",
  "WritingandEditing",
  "StaffingandRecruiting",
  "WholesaleMotorVehiclesandParts",
  "ProfessionalTrainingandCoaching",
  "VentureCapitalandPrivateEquityPrincipals",
  "PoliticalOrganizations",
  "TranslationandLocalization",
  "ComputerGames",
  "EventsServices",
  "RetailArtSupplies",
  "Museums",
  "Appliances,Electrical,andElectronicsManufacturing",
  "OnlineAudioandVideoMedia",
  "WholesaleFurnitureandHomeFurnishings",
  "HistoricalSites",
  "NanotechnologyResearch",
  "RetailArtDealers",
  "Musicians",
  "ZoosandBotanicalGardens",
  "Transportation,Logistics,SupplyChainandStorage",
  "PlasticsManufacturing",
  "ComputerandNetworkSecurity",
  "WirelessServices",
  "AmusementParksandArcades",
  "AlternativeDisputeResolution",
  "SecurityandInvestigations",
  "FacilitiesServices",
  "OutsourcingandOffshoringConsulting",
  "WellnessandFitnessServices",
  "AlternativeMedicine",
  "MediaProduction",
  "AnimationandPost-production",
  "LeasingNon-residentialRealEstate",
  "CapitalMarkets",
  "WholesalePhotographyEquipmentandSupplies",
  "ThinkTanks",
  "PhilanthropicFundraisingServices",
  "GolfCoursesandCountryClubs",
  "E-LearningProviders",
  "Wholesale",
  "WholesaleComputerEquipment",
  "SkiingFacilities",
  "WholesaleImportandExport",
  "IndustrialMachineryManufacturing",
  "Photography",
  "HumanResourcesServices",
  "RetailOfficeEquipment",
  "MentalHealthCare",
  "GraphicDesign",
  "InternationalTradeandDevelopment",
  "BeverageManufacturing",
  "Accommodation",
  "WholesaleMetalsandMinerals",
  "RetailLuxuryGoodsandJewelry",
  "RenewableEnergySemiconductorManufacturing",
  "Glass,CeramicsandConcreteManufacturing",
  "PackagingandContainersManufacturing",
  "HotelsandMotels",
  "AutomationMachineryManufacturing",
  "WholesaleAppliances,Electrical,andElectronics",
  "GovernmentRelationsServices",
  "Bed-and-Breakfasts,Hostels,Homestays",
  "Horticulture",
  "WholesaleHardware,Plumbing,HeatingEquipment",
  "WholesaleMachinery",
  "Caterers",
  "MobileFoodServices",
  "RenewableEnergyPowerGeneration",
  "Bars,Taverns,andNightclubs",
  "RenewableEnergyEquipmentManufacturing",
  "EngineeringServices",
  "ServicesforRenewableEnergy",
  "RepairandMaintenance",
  "VehicleRepairandMaintenance",
  "WholesaleRecyclableMaterials",
  "WholesaleLuxuryGoodsandJewelry",
  "WholesalePaperProducts",
  "ElectronicandPrecisionEquipmentMaintenance",
  "WholesaleDrugsandSundries",
  "WholesaleApparelandSewingSupplies",
  "CommercialandIndustrialMachineryMaintenance",
  "Farming,Ranching,Forestry",
  "ReupholsteryandFurnitureRepair",
  "WholesaleFootwear",
  "WholesaleFoodandBeverage",
  "FootwearandLeatherGoodsRepair",
  "PersonalandLaundryServices",
  "PersonalCareServices",
  "LaundryandDrycleaningServices",
  "WholesaleRawFarmProducts",
  "WholesaleChemicalandAlliedProducts",
  "PetServices",
];
