export default {
  privacyUrlKeywords: [
    "datenschutz",
    "privacy",
    "data-privacy",
    "data-protection",
    "datensicherheit",
    "dsgvo",
    "gdpr",
  ],
  privacyFlags: [
    {
      keywords: [
        "Datenschutzbeauftragter",
        "Datenschutzbeauftragte",
        "Datenschutzbeauftragte/r",
        "Beauftragte für den Datenschutz",
        "Beauftragter für den Datenschutz",
        "Beauftragte/r für den Datenschutz",
        "Beauftragte für Datenschutz",
        "Beauftragter für Datenschutz",
        "Beauftragte/r für Datenschutz",
        "Data Privacy Officer",
        "Data Protection Officer",
      ],
      exactMatch: true,
      expected: true,
      label: "No DPO",
      fullLabel: "Is a Data Protection Officer listed?",
    },
    {
      keywords: ["Privacy Shield"],
      exactMatch: true,
      expected: false,
      label: "EU-US Privacy Shield",
      fullLabel: "Is the EU-US Privacy Shield mentioned?",
    },
    {
      keywords: ["Google Analytics"],
      exactMatch: true,
      expected: false,
      label: "Google Analytics",
      fullLabel: "Is Google Analytics mentioned?",
    },
  ],
  cookieFlags: [
    {
      name: "_ga",
      exactMatch: true,
      expected: false,
      label: "Google Analytics",
      fullLabel: 'Is the "_ga" Google Analytics cookie activated by default?',
    },
    {
      name: "hubspotutk",
      exactMatch: true,
      expected: false,
      label: "HubSpot",
      fullLabel: 'Is the "hubspotuk" HubSpot cookie activated by default?',
    },
  ],
};
